In [33]:
import numpy as np
import pandas as pd

In [2]:
arr1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [4]:
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)

(2, 2, 2)
3
8

In [5]:
arr1[0][0][0]

1

In [7]:
arr1 = [[1,2,3],[4,5,6]]
df1 = pd.DataFrame(arr1)

In [8]:
df1

   0  1  2
0  1  2  3
1  4  5  6

In [16]:
df2 = pd.DataFrame(arr1,columns=["번호","숫자","높이"])

In [19]:
df2

   번호  숫자  높이
0   1   2   3
1   4   5   6

In [25]:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df1 = pd.DataFrame(data)

In [26]:
df1

   A  B
0  1  4
1  2  5
2  3  6

In [32]:
df1["A"].iloc[1]

2

In [41]:
arr = np.random.randint(2,10,size=(2,3))
print(arr)

[[7 9 4]
 [4 5 7]]

In [43]:
print(arr.dtype())

TypeError: 'numpy.dtypes.Int32DType' object is not callable

In [45]:
x = 100
y = 200
add = x+y
print("%d와 %d의 합은 %d입니다"%(x,y,add))

100와 200의 합은 300입니다

In [46]:
a = "hello"
print(a[0:5])

hello

In [47]:
list1 = [1,2,3,4,5]

[1]
[2]
[3]
[4]
[5]
[]

In [56]:
n =5
for i in range(1,n+1):
    print(" "*(n-i)+"*"*(2*i-1))

    *
   ***
  *****
 *******
*********